version: '3.8'

services:
  webhook-service:
    image: ${REGISTRY_URL}/webhook-service:latest
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    environment:
      - REDIS_HOST=redis
    networks:
      - UvepomNet
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: any

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - UvepomNet
    env_file:
      - stack.env
    deploy:
      restart_policy:
        condition: any

  processing-service:
    image: ${REGISTRY_URL}/processing-service:latest
    env_file:
      - stack.env
    environment:
      - REDIS_HOST=redis
    networks:
      - UvepomNet
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: any

  ads-service:
    image: ${REGISTRY_URL}/ads-service:latest
    env_file:
      - stack.env
    networks:
      - UvepomNet
    deploy:
      restart_policy:
        condition: any

volumes:
  redis-data:
    driver: local 

networks:
  UvepomNet:
    external: true